# Generated by Django 4.2.7 on 2023-11-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_remove_user_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='token', max_length=100, verbose_name='token'),
        ),
    ]
