# Generated by Django 4.2.7 on 2023-11-17 13:14

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Содержимое')),
                ('img', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Изображение')),
                ('date_begin', models.DateField(default=django.utils.datetime_safe.date.today, verbose_name='Дата создания')),
                ('activate', models.BooleanField(default=True)),
                ('count_views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
            },
        ),
    ]
