# Generated by Django 4.2.7 on 2023-11-10 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='имя')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='тема')),
                ('text', models.TextField(verbose_name='текст')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('periodic', models.IntegerField(choices=[(1, 'Минута'), (60, 'Час'), (1440, 'День'), (10080, 'Неделя'), (43200, 'Месяц'), (525600, 'Год')], default=1440, verbose_name='периодичность')),
                ('start', models.DateField(default=django.utils.timezone.now, verbose_name='начало')),
                ('stop', models.DateField(blank=True, null=True, verbose_name='окончание')),
                ('status', models.CharField(choices=[('CR', 'Создание'), ('LA', 'Запущена'), ('CP', 'Завершина'), ('PA', 'Пауза')], default='CR', max_length=10, verbose_name='статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('clients', models.ManyToManyField(to='service.client', verbose_name='клиенты')),
                ('massage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.massage', verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_attempt', models.DateField(default=django.utils.timezone.now, verbose_name='время последней попытки')),
                ('status', models.BooleanField(default=False, verbose_name='статус')),
                ('mode', models.CharField(max_length=10, verbose_name='режим')),
                ('mail_server_response', models.CharField(max_length=100, verbose_name='ответ почтового сервера')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.mailing', verbose_name='название')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
            },
        ),
    ]
