# Generated by Django 4.2.7 on 2023-11-16 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_mailing_start_alter_mailing_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='mail_server_response',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ответ почтового сервера'),
        ),
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(max_length=100, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('CR', 'Создание'), ('LA', 'Запущена'), ('CP', 'Завершина'), ('RY', 'Ждет отправки'), ('NA', 'Не активна')], default='NA', max_length=10, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='stop',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 12, 23, 10, 438706), verbose_name='окончание'),
        ),
    ]
