# Generated by Django 4.2.7 on 2023-11-16 08:24

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_log_mail_server_response_alter_log_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time_attempt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время последней попытки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='stop',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 12, 24, 40, 606682), verbose_name='окончание'),
        ),
    ]
