# Generated by Django 4.2.7 on 2023-11-16 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_log_time_attempt_alter_mailing_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(to='service.client', verbose_name='клиенты'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 16, 13, 2, 10, 7138), verbose_name='начало'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='stop',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 13, 2, 10, 23133), verbose_name='окончание'),
        ),
    ]
