# Generated by Django 4.2.7 on 2023-11-16 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_mailing_clients_alter_mailing_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(default='', to='service.client', verbose_name='клиенты'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 16, 13, 5, 17, 262202), verbose_name='начало'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='stop',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 13, 5, 17, 262202), verbose_name='окончание'),
        ),
    ]
