# Generated by Django 4.2.7 on 2023-11-16 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_mailing_clients_alter_mailing_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='start',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='начало'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='stop',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 13, 14, 37, 424174), verbose_name='окончание'),
        ),
    ]
