# Generated by Django 4.2.7 on 2023-11-16 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_mailing_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='stop',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='окончание'),
        ),
    ]
