# Generated by Django 4.2.7 on 2023-11-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_alter_mailing_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(blank=True, to='service.client', verbose_name='клиенты'),
        ),
    ]
