# Generated by Django 4.2.7 on 2023-11-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_mailing_clients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('set_start_mailing', 'Can start mailing')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
