# Generated by Django 4.2.7 on 2023-11-18 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_client_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('set_start_mailing', 'Can start mailing'), ('set_activat_mailing', 'Can activate mailing')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
