# Generated by Django 4.2.7 on 2023-11-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_alter_mailing_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='mode',
            field=models.CharField(max_length=100, verbose_name='режим'),
        ),
    ]
